<?php

namespace App\Modules\Admin\Http\Controllers\Article;

use App\Models\Article\ArticleLabel;
use App\Modules\Admin\Http\Controllers\BaseController;
use App\Modules\Admin\Http\Requests\Article\ArticleLabelRequest;
use Illuminate\Http\JsonResponse;

class ArticleLabelController extends BaseController
{
    protected $model = ArticleLabel::class;

    protected $validator = ArticleLabelRequest::class;

    public function setFiltersWhere($query)
    {
        $request = request();
        // 按照名称进行搜索
        if (!empty($search = $request->input('search', ''))){
            $query->where('label_name', 'LIKE', '%' . trim($search) . '%');
        }
    }

    public function getSelectLists($callback = []): JsonResponse
    {
        return parent::getSelectLists(function($query){
            $search = request()->input('search', '');
            // 可以按照名称进行搜索
            if (!empty($search)){
                $query->where('label_name', 'LIKE', '%' . trim($search) . '%');
            }
        }); // TODO: Change the autogenerated stub
    }
}
